services:
  - type: web
    name: bird-model-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r BackEnd/resnet_model/requirements.txt
    startCommand: uvicorn BackEnd.resnet_model.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
    workingDirectory: BackEnd/resnet_model